BibliotecaWebApplication/BibliotecaWebApplication/Controllers/AutoresController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BibliotecaWebApplication.Data;
using BibliotecaWebApplication.Models;
using Microsoft.AspNetCore.Authorization;

namespace BibliotecaWebApplication.Controllers
{
    public class AutoresController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AutoresController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Autores
        [Authorize(Roles ="Bibliotecario, Administrador")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Autores.ToListAsync());
        }

        // GET: Autores/Details/5
        [Authorize(Roles = "Bibliotecario, Administrador")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autor = await _context.Autores
                .Include(a => a.AutorLibros) // Incluye los libros asociados al autor
                .ThenInclude(al => al.Libro) // Incluye los detalles de los libros
                .FirstOrDefaultAsync(m => m.AutorId == id);

            if (autor == null)
            {
                return NotFound();
            }

            return View(autor);
        }


        // GET: Autores/Create
        [Authorize(Roles = "Administrador")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Create([Bind("AutorId,Nombres,Apellidos,Nacionalidad,FotoUrl")] Autor autor, IFormFile foto)
        {
            //if (ModelState.IsValid)
            {
               

                autor.AutorId = Guid.NewGuid();
                _context.Add(autor);
                await _context.SaveChangesAsync();

                // Detectar si la solicitud es AJAX
                if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    // Retornar un resultado JSON con los detalles del nuevo autor
                    return Json(new { success = true, autor });
                }

                return RedirectToAction(nameof(Index));
            }

            return View(autor);
        }




        // GET: Autores/Edit/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autor = await _context.Autores.FindAsync(id);
            if (autor == null)
            {
                return NotFound();
            }
            return View(autor);
        }

        // POST: Autores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        // POST: Autores/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(Guid id, [Bind("AutorId,Nombres,Apellidos,Nacionalidad,FotoUrl")] Autor autor, IFormFile foto)
        {
            if (id != autor.AutorId)
            {
                return NotFound();
            }

            //if (ModelState.IsValid)
            {
                try
                {
                    var autorExistente = await _context.Autores.AsNoTracking().FirstOrDefaultAsync(a => a.AutorId == id);

                   

                    _context.Update(autor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AutorExists(autor.AutorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(autor);
        }



        // GET: Autores/Delete/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autor = await _context.Autores
                .FirstOrDefaultAsync(m => m.AutorId == id);
            if (autor == null)
            {
                return NotFound();
            }

            return View(autor);
        }

        // POST: Autores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var autor = await _context.Autores.FindAsync(id);
            if (autor != null)
            {
                _context.Autores.Remove(autor);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AutorExists(Guid id)
        {
            return _context.Autores.Any(e => e.AutorId == id);
        }

        [AllowAnonymous]
        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

BibliotecaWebApplication/BibliotecaWebApplication/Controllers/LibrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BibliotecaWebApplication.Data;
using BibliotecaWebApplication.Models;
using Microsoft.AspNetCore.Authorization;

namespace BibliotecaWebApplication.Controllers
{
    public class LibrosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LibrosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Libros
        [Authorize(Roles = "Bibliotecario, Administrador")]
        public async Task<IActionResult> Index()
        {
            var libros = await _context.Libros
                .Include(l => l.AutorLibros)
                    .ThenInclude(al => al.Autor)
                .ToListAsync();
            return View(libros);
        }

        // GET: Libros/Details/5
        [Authorize(Roles = "Bibliotecario, Administrador")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .Include(l => l.AutorLibros)
                    .ThenInclude(al => al.Autor)
                .FirstOrDefaultAsync(m => m.LibroId == id);
            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        // GET: Libros/Create
        [Authorize(Roles = "Administrador")]
        public IActionResult Create()
        {
            ViewBag.Autores = _context.Autores.ToList();
            return View();
        }

        // POST: Libros/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Create([Bind("LibroId,ISBN,Titulo,NumeroPaginas,Formato,PortadaUrl,ContraportadaUrl")] Libro libro, IFormFile portada, IFormFile contraportada, Guid[] selectedAutores)
        {
            //if (ModelState.IsValid)
            {
                var publicacion = new Publicacion
                {
                    PublicacionId = Guid.NewGuid()
                };

                _context.Publicaciones.Add(publicacion);
                await _context.SaveChangesAsync();

                libro.PublicacionId = publicacion.PublicacionId;
                libro.LibroId = Guid.NewGuid();
             
                _context.Add(libro);
                await _context.SaveChangesAsync();

                if (selectedAutores != null)
                {
                    foreach (var autorId in selectedAutores)
                    {
                        var autorLibro = new AutorLibro
                        {
                            AutorId = autorId,
                            LibroId = libro.LibroId
                        };
                        _context.AutorLibros.Add(autorLibro);
                    }
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction(nameof(Index));
            }

            ViewBag.Autores = _context.Autores.ToList();
            return View(libro);
        }



        // GET: Libros/Edit/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .Include(l => l.Publicacion)
                .Include(l => l.AutorLibros)
                    .ThenInclude(al => al.Autor)
                .FirstOrDefaultAsync(m => m.LibroId == id);

            if (libro == null)
            {
                return NotFound();
            }

            ViewBag.Autores = _context.Autores.ToList();
            ViewBag.SelectedAutores = libro.AutorLibros.Select(al => al.AutorId).ToList() ?? new List<Guid>();

            return View(libro);
        }

        // POST: Libros/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(Guid id, [Bind("LibroId,ISBN,Titulo,NumeroPaginas,Formato")] Libro libro, IFormFile portada, IFormFile contraportada, Guid[] selectedAutores)
        {
            if (id != libro.LibroId)
            {
                return NotFound();
            }

            //if (ModelState.IsValid)
            {
                try
                {
                    var libroFromDb = await _context.Libros
                        .Include(l => l.Publicacion)
                        .FirstOrDefaultAsync(l => l.LibroId == id);

                    if (libroFromDb == null)
                    {
                        return NotFound();
                    }

                    libroFromDb.ISBN = libro.ISBN;
                    libroFromDb.Titulo = libro.Titulo;
                    libroFromDb.NumeroPaginas = libro.NumeroPaginas;
                    libroFromDb.Formato = libro.Formato;

                    

                    _context.Update(libroFromDb);
                    await _context.SaveChangesAsync();

                    var existingAutorLibros = _context.AutorLibros.Where(al => al.LibroId == id);
                    _context.AutorLibros.RemoveRange(existingAutorLibros);

                    if (selectedAutores != null && selectedAutores.Any())
                    {
                        foreach (var autorId in selectedAutores)
                        {
                            var autorLibro = new AutorLibro
                            {
                                AutorId = autorId,
                                LibroId = libro.LibroId
                            };
                            _context.AutorLibros.Add(autorLibro);
                        }
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LibroExists(libro.LibroId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Autores = _context.Autores.ToList();
            ViewBag.SelectedAutores = selectedAutores != null ? selectedAutores.ToList() : new List<Guid>();
            return View(libro);
        }


        private bool LibroExists(Guid id)
        {
            return _context.Libros.Any(e => e.LibroId == id);
        }



        // GET: Libros/Delete/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var libro = await _context.Libros
                .Include(l => l.AutorLibros)
                    .ThenInclude(al => al.Autor)
                .FirstOrDefaultAsync(m => m.LibroId == id);
            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var libro = await _context.Libros
                .Include(l => l.AutorLibros)
                .Include(l => l.Publicacion) // Incluye la Publicacion asociada
                .FirstOrDefaultAsync(l => l.LibroId == id);

            if (libro != null)
            {
                // Eliminar relaciones en AutorLibro
                _context.AutorLibros.RemoveRange(libro.AutorLibros);

                // Eliminar la publicacion asociada
                if (libro.Publicacion != null)
                {
                    _context.Publicaciones.Remove(libro.Publicacion);
                }

                // Eliminar el libro
                _context.Libros.Remove(libro);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

BibliotecaWebApplication/BibliotecaWebApplication/Controllers/RolesController.cs
using BibliotecaWebApplication.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace BibliotecaWebApplication.Controllers
{
    [Authorize(Roles = "Root")]
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        // GET: RolesConroller 
        public async Task<ActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }

        // GET: RolesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RolesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole role = new IdentityRole { Name = model.Name };
                IdentityResult result = await _roleManager.CreateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

            }
            return View(model);
        }

        // GET: RolesController/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            RoleViewModel model = new RoleViewModel { Id = role.Id, Name = role.Name };
            return View(model);
        }

        // POST: RolesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = await _roleManager.FindByIdAsync(model.Id);
                if (role == null)
                {
                    return NotFound();
                }
                role.Name = model.Name;
                var result = await _roleManager.UpdateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Root")]
        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                var result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", new { deletionSuccess = true });
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View("Index");
        }

        [AllowAnonymous]
        public IActionResult AccessDenied()
        {
            return View();
        }

    }
}

BibliotecaWebApplication/BibliotecaWebApplication/Views/Shared/AccessDenied.cshtml
@{
    ViewBag.Title = "Acceso Denegado";
}


<h1>Acceso Denegado</h1>
<p>No tienes permisos para acceder a esta página.</p>

<a asp-controller="Home" asp-action="Index" class="btn btn-back"><i class="fas fa-arrow-left"></i> Volver</a>

BibliotecaWebApplication/BibliotecaWebApplication/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Biblioteca</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BibliotecaWebApplicationMVC.styles.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.3/css/dataTables.dataTables.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">BibliotecaWebApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            var user = await UserManager.GetUserAsync(User);
                            if (user != null && (await UserManager.IsInRoleAsync(user, "Bibliotecario") || await UserManager.IsInRoleAsync(user, "Administrador")))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Gestionar Libros
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <li><a class="dropdown-item text-dark" asp-area="" asp-controller="Autores" asp-action="Index"> Autores</a></li>
                                        <li><a class="dropdown-item text-dark" asp-area="" asp-controller="Libros" asp-action="Index"> Libros</a></li>
                                    </ul>
                                </li>
                            }
                        }

                        @if (User.Identity.IsAuthenticated)
                        {
                            var user = await UserManager.GetUserAsync(User);
                            if (user != null && (await UserManager.IsInRoleAsync(user, "Bibliotecario") || await UserManager.IsInRoleAsync(user, "Administrador")))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Gestionar Estanterias
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <li><a class="dropdown-item text-dark" asp-area="" asp-controller="Estanterias" asp-action="Index"> Estanterias</a></li>
                                        <li><a class="dropdown-item text-dark" asp-area="" asp-controller="Estantes" asp-action="Index"> Estantes</a></li>
                                        <li><a class="dropdown-item text-dark" asp-area="" asp-controller="Ejemplares" asp-action="Index"> Ejemplares</a></li>
                                        <li><a class="dropdown-item text-dark" asp-area="" asp-controller="Revistas" asp-action="Index"> Revistas</a></li>
                                    </ul>
                                </li>
                            }
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            var user = await UserManager.GetUserAsync(User);
                            if (user != null && (await UserManager.IsInRoleAsync(user, "Root")))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Administrar Roles y Usuarios
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <li><a class="dropdown-item text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a></li>
                                        <li><a class="dropdown-item text-dark" asp-area="" asp-controller="UserRoles" asp-action="Index">Usuarios Roles</a></li>
                                    </ul>
                                </li>
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-light bg-dark">
        <div class="container">
            &copy; 2024 - BibliotecaWebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-warning">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Data Table-->
    <script src="https://cdn.datatables.net/2.1.3/js/dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- sweet Alert-->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>



    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>